name: Build JavaScript Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    permissions:
      security-events: write # Used to upload Sarif artifact to GitHub
      contents: read # Used to check out a private repository
      actions: read # Required for private repositories to upload Sarif files. GitHub Advanced Security licenses are required.
      pull-requests: write # Required to automatically comment on PRs for new policy violations
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'microsoft'
        java-version: '17'
    - uses: actions/checkout@v3
    - name: Scan with Endor Labs
      uses: endorlabs/github-action@v1.1.4
      with:
        namespace: 'sanity-debug'
        api: 'https://app.staging.endorlabs.com'
        api_key: ${{ secrets.ENDOR_API_CREDENTIALS_KEY }}
        api_secret: ${{ secrets.ENDOR_API_CREDENTIALS_SECRET }}
        enable_github_action_token: false
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14' # You can specify the Node.js version you need

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build
    
        
